services:
  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  mysql_data:

    